### ISSUE TITLE
How to use the package!

### ISSUE THREAD

**Issue by sinamr88** [NMMI/ROS-SoftHand#1]
Hi All,

By following the provided tutorial, I have already tried for several hours to send send a simple opening and closing command to hand, but I have failed!.. Based on the tutorial this topic should be used for sending commands to the hand:
```
/qbhand1/control/qbhand1_synergy_trajectory_controller/command
/qbhand1/control/qbhand1_synergy_trajectory_controller/follow_joint_trajectory/goal
```
However any command I send results in 
```
[ERROR] [1545057161.382162159]: Joints on incoming goal don't match the controller joints.
[ERROR] [1545057182.907966187]: Joints on incoming goal don't match the controller joints.
```
Can you provide a simple **rostopic pub** example????

Thanks
Best
Sina

**Comment by qbrobotics-AT** [comment]
Hello @sinamr66, 

I assume you are launching the control node for the hand in a way similar to the following:
```
roslaunch qb_hand_control control.launch standalone:=true activate_on_initialization:=true device_name:=my_hand
```

If so, you just need to use the right name of the _virtual_ joint (which control the percent position closure of the _qb SoftHand_) when sending the command to the hand, e.g.
```
rostopic pub -1 /my_hand/control/my_hand_synergy_trajectory_controller/command trajectory_msgs/JointTrajectory "header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: ''
joint_names:
- 'my_hand_synergy_joint'
points:
- positions: [0.5]
  velocities: [0]
  accelerations: [0]
  effort: [0]
  time_from_start: {secs: 1, nsecs: 0}"
```

Please, let me know if this works.

Best regards,
Alessandro Tondo
